name: Workflow name

on: push

permissions:
  contents: read

jobs:
  test:
    name: Run test with multiple configurations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number_of_cities: [30, 50]
        delta: [0.3, 0.6]
        alpha: ['[0.5, 0.3, 0.1]', '[0.3, 0.2, 0.1]']
        end_segment: [50, 100, 150]
        iteration: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # Thêm biến iteration để lặp job 10 lần
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Run main.py
        run: python 1_0.3.py
        env:
          NUMBER_OF_CITIES: ${{ matrix.number_of_cities }}
          DELTA: ${{ matrix.delta }}
          ALPHA: ${{ matrix.alpha }}
          END_SEGMENT: ${{ matrix.end_segment }}

      - name: Upload result Excel file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-results-${{ matrix.number_of_cities }}-${{ matrix.delta }}-${{ matrix.alpha }}-${{ matrix.end_segment }}-${{ matrix.iteration }}  # Thêm iteration vào tên file
          path: Random_*_CL1.xlsx

  summary:
    name: Summary results
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-results-summary
          path: Random_*_CL1.xlsx
