name: Workflow name

on: push

permissions:
  contents: read

jobs:
  test:
    name: Run test with multiple configurations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number_of_cities: [10]
        delta: [0.3, 0.6]
        alpha: ['[0.5, 0.3, 0.1]', '[0.3, 0.2, 0.1]']
        end_segment: [50, 100, 150]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Run main.py
        run: python 1_0.3.py > Random_${{ matrix.number_of_cities }}_${{ matrix.delta }}_${{ matrix.alpha}}_${{ matrix.end_segment }}_CL1.xlsx
        env:
          NUMBER_OF_CITIES: ${{ matrix.number_of_cities }}
          DELTA: ${{ matrix.delta }}
          ALPHA: ${{ matrix.alpha }}
          END_SEGMENT: ${{ matrix.end_segment }}
      - name: Check
        run: ls
      - name: Upload result Excel file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: excel-results-${{ matrix.number_of_cities }}-${{ matrix.delta }}-${{ matrix.alpha }}-${{ matrix.end_segment }}
          path: Random_${{ matrix.number_of_cities }}_${{ matrix.delta }}_${{ matrix.alpha}}_${{ matrix.end_segment }}_CL1.xlsx